Repository JWalshe86/2312-hackathon-team5, pull requests merged in 2023-12, with the labels that each got.

#11 README: Instructions for branching
  README.md
  documentation/readme_images/branch-label.png
  documentation/readme_images/three-dot.png
  documentation/readme_images/unmissable-message.png
Labels: documentation

#14 Add mobile wireframe image
  assets/Wireframes-mobile.png
Labels: must have

#25 JS code functionality corrections + various other things
  assets/js/script.js
  index.html
Labels: enhancement

#30 Add favicon.png to index.html in multiple sizes
  README.md
  favicon.png
  index.html
Labels: documentation, enhancement

#44 Feature: Progress Bar functionality
  assets/js/script.js
  index.html
Labels: enhancement

#45 Feature: Interface manipulation
  assets/css/style.css
  assets/images/bag of coal.jpg
  assets/images/banana costume.jpg
  assets/images/big cat teddy.webp
  assets/images/chicken leg socks.webp
  assets/images/pack of ham.jpg
  assets/images/propeller hat.webp
  assets/images/rubber chicken.jpg
  assets/images/shrek dvd.jpg
  assets/images/turkey hat.jpg
  assets/js/script.js
  index.html
Labels: enhancement

#46 Refactor form submission handling function and add dependencies for v…
  assets/images/voucher-template.png
  assets/js/script.js
  assets/wireframes/Wireframes-mobile.png
  index.html
Labels: bug

#48 Various: Gift-Image association, image sizing, navbar improvements
  about.html
  assets/css/style.css
  assets/images/santa icon.png
  assets/js/script.js
  index.html
Labels: enhancement

#49 Documentation: README scaffolding
  README.md
Labels: documentation

#52 Bug fix
  assets/js/script.js
Labels: bug

#53 Add customisable snowfall effect to both pages
  about.html
  assets/js/script.js
  index.html
Labels: enhancement

#55 Keiron branch: Various changes
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement

#56 Add wireframes to readme and change social links to white
  README.md
  assets/css/style.css
Labels: documentation, enhancement

#64 Keiron; README
  README.md
  documentation/existing_features/about-us.png
  documentation/existing_features/christmas-tree.png
  documentation/existing_features/footer.png
  documentation/existing_features/input-field.png
  documentation/existing_features/instructions-button.png
  documentation/existing_features/landing-page.png
  documentation/existing_features/progress-bar.png
  documentation/readme_images/amiresponsive.png
Labels: documentation

#63 Fonts and vouchers updated, favicon added to 'About Us' page
  README.md
  about.html
  assets/css/style.css
  assets/vouchers/vouchers.pdf
  assets/wireframes/wireframe-vouchers.jpg
  index.html
Labels: documentation, enhancement

#68 Documentation: Restore README.md after weird merge
  README.md
Labels: bug, documentation

#69 Documentation: README updates
  README.md
  documentation/readme_images/colour-palette.png
  documentation/readme_images/lighthouse-testing.png
Labels: documentation

#70 Cleanup: Run Prettier across HTML, CSS and JS files
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement

#77 README: Testing + validations
  README.md
  about.html
  assets/css/style.css
  assets/images/santa_icon.png
  documentation/testing/CSS-validator-results.png
  documentation/testing/HTML-validator-results-about-page.png
  documentation/testing/HTML-validator-results.png
  index.html
Labels: documentation, enhancement

#78 Keiron "Plan B" Branch : merge into main branch
  about.html
  assets/css/style.css
  assets/js/script.js
  assets/js/voucher.js
  assets/vouchers/cheeky-banana.png
  assets/vouchers/cheeky-big-boi-cat-teddy.png
  assets/vouchers/cheeky-chicken.png
  assets/vouchers/cheeky-coal.png
  assets/vouchers/cheeky-ham.png
  assets/vouchers/cheeky-hat.png
  assets/vouchers/cheeky-shrek.png
  assets/vouchers/cheeky-socks.png
  assets/vouchers/cheeky-turkey-hat.png
  assets/vouchers/vouchers.pdf
  index.html
Labels: enhancement
